// Seed / fallback data — matches the exact shape returned by GET /api/listings
// (see api/sheets.py _row_to_listing). Used when the API is unreachable so the
// site never renders blank.

export const SEED_LISTINGS = [
  { id: "sd-1", title: "Frontend Developer Intern", org: "Razorpay", editor: "Ananya Iyer", cluster: "Software", location: "Bangalore", type: "Hybrid", timing: "Full-time", stipend: 40000, duration: "6 months", experience: "Fresher", deadline: "2026-07-05", hoursAgo: 1, score: 94, tags: ["React", "TypeScript", "Fintech"], subchips: ["Frontend", "Web", "UI Developer"], similar: ["Full Stack", "UI/UX", "Mobile"], contact: "campus@razorpay.com", applyLink: "", postUrl: "https://www.linkedin.com/feed/", desc: "Build merchant-facing dashboards used by millions of businesses. Ship production React against an in-house design system, paired with senior engineers." },
  { id: "sd-2", title: "Data Science Intern", org: "Zomato", editor: "Rohit Mehta", cluster: "Data/AI", location: "Gurgaon", type: "Onsite", timing: "Full-time", stipend: 35000, duration: "6 months", experience: "Fresher", deadline: "2026-07-03", hoursAgo: 3, score: 91, tags: ["Python", "ML", "Analytics"], subchips: ["Data Science", "ML", "Analytics"], similar: ["Machine Learning", "Data Engineering"], contact: "talent@zomato.com", applyLink: "", postUrl: "https://www.linkedin.com/feed/", desc: "Work on demand-forecasting and delivery-time models against live order data. Python and SQL expected." },
  { id: "sd-3", title: "UI/UX Design Intern", org: "CRED", editor: "Priya Nair", cluster: "Design", location: "Bangalore", type: "Hybrid", timing: "Full-time", stipend: 30000, duration: "4 months", experience: "Fresher", deadline: "2026-07-08", hoursAgo: 2, score: 90, tags: ["Figma", "Product Design"], subchips: ["UI/UX", "Product Design"], similar: ["Graphic Design", "Product"], contact: "design@cred.club", applyLink: "", postUrl: "https://www.linkedin.com/feed/", desc: "Craft flows for one of India's most design-led fintechs. Prototype in Figma, run usability sessions, defend decisions in critique." },
  { id: "sd-4", title: "Product Management Intern", org: "Groww", editor: "Karan Shah", cluster: "Product", location: "Bangalore", type: "Hybrid", timing: "Full-time", stipend: 45000, duration: "6 months", experience: "Fresher", deadline: "2026-07-02", hoursAgo: 5, score: 89, tags: ["Fintech", "Strategy"], subchips: ["Product", "APM", "Growth PM"], similar: ["Business Dev", "Data/AI"], contact: "pm@groww.in", applyLink: "", postUrl: "https://www.linkedin.com/feed/", desc: "Own a slice of the investing experience used by millions. Write specs, interview users, ship with engineering, measure impact." },
  { id: "sd-5", title: "Machine Learning Intern", org: "Ola", editor: "Sneha Rao", cluster: "Data/AI", location: "Bangalore", type: "Onsite", timing: "Full-time", stipend: 42000, duration: "6 months", experience: "Fresher", deadline: "2026-07-04", hoursAgo: 4, score: 88, tags: ["PyTorch", "ML"], subchips: ["ML", "Deep Learning"], similar: ["Data Science", "Research"], contact: "ml@olacabs.com", applyLink: "", postUrl: "https://www.linkedin.com/feed/", desc: "Improve routing and arrival-time models that move millions of rides a day. Prototype in PyTorch; work reaches production traffic." },
  { id: "sd-6", title: "Marketing Intern", org: "Zepto", editor: "Aditi Verma", cluster: "Marketing", location: "Mumbai", type: "Onsite", timing: "Full-time", stipend: 25000, duration: "3 months", experience: "Fresher", deadline: "2026-06-30", hoursAgo: 6, score: 86, tags: ["Growth", "Performance"], subchips: ["Marketing", "Growth"], similar: ["Content", "Brand"], contact: "growth@zepto.com", applyLink: "", postUrl: "https://www.linkedin.com/feed/", desc: "Run performance campaigns for ten-minute delivery. Own budgets, read dashboards daily, learn paid acquisition." },
  { id: "sd-7", title: "Backend Engineer Intern", org: "Meesho", editor: "Vikram Reddy", cluster: "Software", location: "Bangalore", type: "Hybrid", timing: "Full-time", stipend: 40000, duration: "6 months", experience: "Fresher", deadline: "2026-07-06", hoursAgo: 7, score: 85, tags: ["Node.js", "Distributed"], subchips: ["Backend", "API"], similar: ["Full Stack", "DevOps"], contact: "eng@meesho.com", applyLink: "", postUrl: "https://www.linkedin.com/feed/", desc: "Build APIs that absorb festival-season traffic. Queues, caching, and the kind of scale that exposes naive code." },
  { id: "sd-8", title: "Content Writer Intern", org: "Unacademy", editor: "Meera Pillai", cluster: "Content", location: "Remote", type: "Remote", timing: "Part-time", stipend: 18000, duration: "3 months", experience: "Fresher", deadline: "2026-07-10", hoursAgo: 6, score: 84, tags: ["Content", "SEO"], subchips: ["Content", "Copywriting"], similar: ["Marketing", "Editorial"], contact: "content@unacademy.com", applyLink: "", postUrl: "https://www.linkedin.com/feed/", desc: "Write learner-facing material that ranks and converts. Keyword research, editing, and a clear voice for students." },
  { id: "sd-9", title: "Finance Intern", org: "Zerodha", editor: "Sanjay Gupta", cluster: "Finance", location: "Bangalore", type: "Onsite", timing: "Full-time", stipend: 30000, duration: "4 months", experience: "Fresher", deadline: "2026-07-03", hoursAgo: 8, score: 82, tags: ["Equity Research", "Markets"], subchips: ["Finance", "Analyst"], similar: ["Data/AI", "Strategy"], contact: "careers@zerodha.com", applyLink: "", postUrl: "https://www.linkedin.com/feed/", desc: "Sit with the research desk at India's largest broker. Build models, draft notes, learn how markets price risk." },
  { id: "sd-10", title: "Business Development Intern", org: "Cars24", editor: "Arjun Malhotra", cluster: "Business Dev", location: "Remote", type: "Remote", timing: "Full-time", stipend: 20000, duration: "3 months", experience: "Fresher", deadline: "2026-07-12", hoursAgo: 9, score: 80, tags: ["B2B Sales", "Partnerships"], subchips: ["Business Dev", "Sales"], similar: ["Sales", "Operations"], contact: "bd@cars24.com", applyLink: "", postUrl: "https://www.linkedin.com/feed/", desc: "Build the dealer-partner pipeline. Outreach, demonstrations, and closing — a quick education in how revenue is made." },
  { id: "sd-11", title: "Human Resources Intern", org: "Swiggy", editor: "Deepika Menon", cluster: "HR", location: "Bangalore", type: "Hybrid", timing: "Full-time", stipend: 22000, duration: "4 months", experience: "Fresher", deadline: "2026-07-07", hoursAgo: 11, score: 78, tags: ["Recruiting", "People Ops"], subchips: ["HR", "Recruiting"], similar: ["Operations", "Content"], contact: "people@swiggy.in", applyLink: "", postUrl: "https://www.linkedin.com/feed/", desc: "Support campus hiring at scale. Coordinate drives, screen candidates, and see how a large organisation grows." },
  { id: "sd-12", title: "Graphic Design Intern", org: "PhonePe", editor: "Ishita Sharma", cluster: "Design", location: "Pune", type: "Hybrid", timing: "Full-time", stipend: 25000, duration: "4 months", experience: "Fresher", deadline: "2026-07-09", hoursAgo: 6, score: 75, tags: ["Branding", "Figma"], subchips: ["Graphic Design", "Visual"], similar: ["UI/UX", "Motion"], contact: "brand@phonepe.com", applyLink: "", postUrl: "https://www.linkedin.com/feed/", desc: "Design campaign and product assets for a large payments app. A strong sense of type and a clean grid go a long way." },
];

export const SEED_STATS = {
  verifiedToday: 82,
  spikedToday: 287,
  indiaEligible: 100,
  no: 412,
  vol: "I",
};
